service: dubsserver3
plugins:
  - serverless-dotenv-plugin

provider:
  name: aws
  region: us-west-2
  runtime: nodejs12.x
  stage: dev
  environment:
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}

functions:
  GetPosts:
    handler: handlers/Posts/GetPosts.handler
    events:
      - http:
          method: GET
          path: /api

# only include the Prisma binary required on AWS Lambda while packaging
package:
  patterns:
    - "!node_modules/.prisma/client/libquery_engine-*"
    - "node_modules/.prisma/client/libquery_engine-rhel-*"
    - "!node_modules/prisma/libquery_engine-*"
    - "!node_modules/@prisma/engines/**"
