service: dubsserver3
plugins:
  - serverless-dotenv-plugin

provider:
  name: aws
  region: us-west-2
  runtime: nodejs12.x
  stage: dev
  environment:
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}

functions:
  GetPosts:
    handler: handlers/Posts/GetPosts.handler
    events:
      - http:
          method: GET
          path: /posts
  CreatePost:
    handler: handlers/Posts/CreatePost.handler
    events:
      - http:
          method: POST
          path: /posts
  GetThreads:
    handler: handlers/Thread/GetThreads.handler
    events:
      - http:
          method: GET
          path: /thread
  CreateThread:
    handler: handlers/Thread/CreateThread.handler
    events:
      - http:
          method: POST
          path: /thread
  GetUsers:
    handler: handlers/User/GetUsers.handler
    events:
      - http:
          method: GET
          path: /user
  CreateUser:
    handler: handlers/User/CreateUser.handler
    events:
      - http:
          method: POST
          path: /user
          cors: true

# only include the Prisma binary required on AWS Lambda while packaging
package:
  patterns:
    - "!node_modules/.prisma/client/libquery_engine-*"
    - "node_modules/.prisma/client/libquery_engine-rhel-*"
    - "!node_modules/prisma/libquery_engine-*"
    - "!node_modules/@prisma/engines/**"
